all:
	g++ -Wall -std=gnu++11 -static -o gpa_matching gpa_matching.cpp -L../lib/ -lgpa_matching -largtable2

debug:
	g++ -Wall -std=gnu++11 -static -o gpa_matching gpa_matching.cpp -g -L../lib/ -lgpa_matching -largtable2

original:
	g++ -Wall -std=gnu++11 -static -o gpa_matching_original gpa_matching_original.cpp -g -L../lib/ -lgpa_matching -largtable2

original-debug:
	g++ -Wall -std=gnu++11 -static -o gpa_matching_original gpa_matching_original.cpp -g -L../lib/ -lgpa_matching -largtable2

